"""Binding routes — device generates QR/code, parent links device to their account.
One device → one parent. Device gets a 32-char token for all subsequent auth.
Unbind = invalidate token (is_active=False + new token)."""
from datetime import datetime, timezone
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from app.database import get_db
from app.config import settings
from app.models.parent import Parent
from app.models.child import Child
from app.models.device import Device
from app.schemas.binding import (
    DeviceGenerateRequest, DeviceGenerateResponse,
    DeviceVerifyRequest, DeviceUnbindRequest,
    DeviceBindResult, DeviceStatusOut, DeviceChildOut,
    DeviceCreateChildRequest,
)
from app.utils.qr import generate_device_bind_token, verify_device_bind_token
from app.utils.bind_code import store_bind_code, lookup_bind_code
from app.utils.grade import grade_label
from app.routers.deps import get_current_parent

router = APIRouter(prefix="/api/binding", tags=["binding"])


# ─── Child device: generate QR / bind code ───

@router.post("/device/generate", response_model=DeviceGenerateResponse)
def device_generate(req: DeviceGenerateRequest):
    """Child device generates a QR token + short bind code for parent to scan."""
    token, expires_at = generate_device_bind_token(req.device_uuid)
    expires_ts = expires_at.timestamp()
    code = store_bind_code(token, 0, expires_ts)
    return DeviceGenerateResponse(
        qr_token=token,
        bind_code=code,
        expires_at=expires_at.isoformat(),
    )


# ─── Parent: scan QR / enter code to link device ───

@router.post("/device/verify", response_model=DeviceBindResult)
def device_verify(
    payload: DeviceVerifyRequest,
    parent: Parent = Depends(get_current_parent),
    db: Session = Depends(get_db),
):
    """Parent links a device to their account. Generates device_token for child auth."""
    qr_token = payload.qr_token
    if not qr_token and payload.bind_code:
        qr_token = lookup_bind_code(payload.bind_code)
        if not qr_token:
            raise HTTPException(status_code=400, detail="綁定碼無效或已過期")
    if not qr_token:
        raise HTTPException(status_code=400, detail="請提供 QR 碼或綁定碼")

    data = verify_device_bind_token(qr_token)
    if data is None:
        raise HTTPException(status_code=400, detail="綁定碼無效或已過期")

    device_uuid = data["device_uuid"]

    # Check if device already bound
    existing = db.query(Device).filter(Device.device_uuid == device_uuid).first()
    if existing:
        if existing.parent_id == parent.id:
            if not existing.is_active:
                # Re-activate
                existing.is_active = True
                existing.unbound_at = None
                db.commit()
            children_count = db.query(Child).filter(Child.parent_id == parent.id).count()
            return DeviceBindResult(
                success=True, device_uuid=device_uuid,
                device_token=existing.device_token,
                parent_email=parent.email, children_count=children_count,
                message="設備已綁定到你的帳號",
            )
        raise HTTPException(status_code=400, detail="此設備已綁定到其他家長帳號")

    # Check max devices per parent
    device_count = db.query(Device).filter(
        Device.parent_id == parent.id, Device.is_active == True
    ).count()
    if device_count >= settings.MAX_DEVICES_PER_PARENT:
        raise HTTPException(
            status_code=400,
            detail=f"已達最大設備數限制（{settings.MAX_DEVICES_PER_PARENT}台）",
        )

    # Link device — device_token auto-generated by model default
    device = Device(device_uuid=device_uuid, parent_id=parent.id, is_active=True)
    db.add(device)
    db.commit()
    db.refresh(device)

    children_count = db.query(Child).filter(Child.parent_id == parent.id).count()
    return DeviceBindResult(
        success=True, device_uuid=device_uuid,
        device_token=device.device_token,
        parent_email=parent.email, children_count=children_count,
        message=f"設備綁定成功！已有 {children_count} 名子女",
    )


# ─── Device: poll status (get token after parent binds) ───

@router.get("/device/{device_uuid}/status", response_model=DeviceStatusOut)
def device_status(device_uuid: str, db: Session = Depends(get_db)):
    """Check if device is bound. Returns device_token for child to store."""
    device = db.query(Device).filter(
        Device.device_uuid == device_uuid, Device.is_active == True
    ).first()
    if not device:
        return DeviceStatusOut(bound=False)
    children_count = db.query(Child).filter(Child.parent_id == device.parent_id).count()
    return DeviceStatusOut(
        bound=True,
        device_token=device.device_token,
        parent_email=device.parent.email if device.parent else "",
        children_count=children_count,
    )


# ─── Device: list children (requires device_token) ───

@router.get("/device/{device_uuid}/children", response_model=list[DeviceChildOut])
def device_list_children(device_uuid: str, db: Session = Depends(get_db)):
    """List all children of the parent that this device is bound to."""
    device = db.query(Device).filter(
        Device.device_uuid == device_uuid, Device.is_active == True
    ).first()
    if not device:
        return []
    children = db.query(Child).filter(Child.parent_id == device.parent_id).all()
    result = []
    for c in children:
        result.append(DeviceChildOut(
            id=c.id, name=c.name, avatar=c.avatar,
            grade=c.grade, grade_label=grade_label(c.grade),
            parent_email=device.parent.email if device.parent else "",
            total_questions=c.total_questions,
            total_correct=c.total_correct,
        ))
    return result


# ─── Device: create a child for the bound parent ───

@router.post("/device/{device_uuid}/children", response_model=DeviceChildOut, status_code=201)
def device_create_child(
    device_uuid: str,
    payload: DeviceCreateChildRequest,
    db: Session = Depends(get_db),
):
    """Child device creates a new user (child) for the bound parent."""
    device = db.query(Device).filter(
        Device.device_uuid == device_uuid, Device.is_active == True
    ).first()
    if not device:
        raise HTTPException(status_code=401, detail="設備未綁定或已失效")

    # Check max children
    count = db.query(Child).filter(Child.parent_id == device.parent_id).count()
    if count >= settings.MAX_CHILDREN_PER_PARENT:
        raise HTTPException(status_code=400, detail=f"已達最大用戶數限制（{settings.MAX_CHILDREN_PER_PARENT}名）")

    now = datetime.utcnow()
    child = Child(
        parent_id=device.parent_id,
        name=payload.name,
        grade=payload.grade or 0,
        avatar=payload.avatar or "🐻",
        grade_set_at=now,
        bound_at=now,
    )
    db.add(child)
    db.commit()
    db.refresh(child)
    return DeviceChildOut(
        id=child.id, name=child.name, avatar=child.avatar,
        grade=child.grade, grade_label=grade_label(child.grade),
        parent_email=device.parent.email if device.parent else "",
        total_questions=0, total_correct=0,
    )


# ─── Parent: list / unlink devices ───

@router.get("/devices")
def list_devices(parent: Parent = Depends(get_current_parent), db: Session = Depends(get_db)):
    """Parent lists all linked devices (active only)."""
    devices = db.query(Device).filter(
        Device.parent_id == parent.id, Device.is_active == True
    ).all()
    return [
        {
            "id": d.id,
            "device_uuid": d.device_uuid,
            "bound_at": d.bound_at.isoformat() if d.bound_at else None,
        }
        for d in devices
    ]


@router.delete("/device/{device_uuid}")
def parent_unlink_device(
    device_uuid: str,
    parent: Parent = Depends(get_current_parent),
    db: Session = Depends(get_db),
):
    """Parent unlinks a device — invalidates the token."""
    device = db.query(Device).filter(
        Device.device_uuid == device_uuid,
        Device.parent_id == parent.id,
    ).first()
    if not device:
        raise HTTPException(status_code=404, detail="找不到設備")
    device.invalidate()
    db.commit()
    return {"success": True, "message": "已解除設備綁定，設備令牌已失效"}


# ─── Device: unbind self ───

@router.post("/device/unbind")
def device_unbind(payload: DeviceUnbindRequest, db: Session = Depends(get_db)):
    """Device unbinds itself — invalidates own token."""
    device = db.query(Device).filter(Device.device_uuid == payload.device_uuid).first()
    if not device:
        raise HTTPException(status_code=404, detail="找不到綁定記錄")
    device.invalidate()
    db.commit()
    return {"success": True, "message": "已解除綁定"}
